# Generated by Django 4.2.11 on 2024-05-03 01:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nonprofits", "0002_remove_nonprofit_address_alter_nonprofit_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="nonprofit",
            name="address",
            field=models.TextField(default=""),
        ),
    ]
